[theme]
primaryColor = '#ff79c6'  # Light pink for primary elements
backgroundColor = '#1e1e2f'  # Darker background for a sleek look
secondaryBackgroundColor = '#282a36'  # Secondary background for a subtle contrast
textColor = '#f8f8f2'  # Light gray for text readability
font = "monospace"  # Modern monospace for a tech-inspired look
